import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';     import './lang'
import { langData, setLanguageData } from './lang';

const inter = Inter( { subsets: ['latin'] } )

export const metadata: Metadata = {
    description: 'Generated by create next app.'
}

export default async function RootLayout( { children }: { children: React.ReactNode } ) {

    await setLanguageData()

    metadata.title = langData.metatitle

    return (
        <html lang="en">
            <body className={ inter.className }>{children}</body>
        </html>
    )
    
}
